services:
  main:
    build: .
    env_file:
      - config/.env
    environment:
      DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    ports:
      -"8181:8181"
    command: go run cmd/main.go -b 0.0.0.0
    depends_on:
      - db
    networks:
      - my_networks
  db:
    restart: always
    image: postgres:14.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DATABASE=${DB_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - my_networks
networks:
  my_networks:
    driver: bridge
#volumes:
#  postgres: